In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('data.csv')[['label', 'regex']]
df['label'] = 'translate English to Regex: ' + df['label']
df

,label,regex
0,translate English to Regex: lines with a chara...,"(..*[a-z].*){6,}"
1,translate English to Regex: lines with a capit...,([A-Z].*..*).*([A-Za-z]).*
2,translate English to Regex: lines with a lower...,(([a-z])&([A-Za-z])).*([0-9]).*
3,translate English to Regex: lines with a chara...,"(..*[0-9].*){6,}"
4,translate English to Regex: lines with the str...,((dog)|([A-Z])).*(.).*
...,...,...
329038,translate English to Regex: lines with the str...,"((dog){6,})|((truck)(.*))"
329039,translate English to Regex: lines not having a...,"~(([A-Z]).*((dog){3,}).*)"
329040,translate English to Regex: lines with the str...,((dog).*([AEIOUaeiou]).*)|((truck)&(ring))
329041,translate English to Regex: lines with the str...,((dog)|([AEIOUaeiou])).*((truck)|([a-z])|(ring...
329042,translate English to Regex: lines not containi...,.*~([A-Z].*dog.*).*

In [45]:
df.to_csv("labeled_data.csv", index=None)

In [23]:
df.columns

Index(['label', ' something', ' regex', ' 0', ' 1', ' 2', ' 3', ' 4'], dtype='object')

In [44]:
df.loc[2][' regex']

KeyError: ' regex'

In [6]:
new_df = df.drop_duplicates()
new_df

,label,regex
0,translate English to Regex: lines with a chara...,"(..*[a-z].*){6,}"
1,translate English to Regex: lines with a capit...,([A-Z].*..*).*([A-Za-z]).*
2,translate English to Regex: lines with a lower...,(([a-z])&([A-Za-z])).*([0-9]).*
3,translate English to Regex: lines with a chara...,"(..*[0-9].*){6,}"
4,translate English to Regex: lines with the str...,((dog)|([A-Z])).*(.).*
...,...,...
329024,translate English to Regex: lines with a lette...,"(([A-Za-z]){5,})|(([0-9])&(dog)&([A-Z]))"
329025,translate English to Regex: lines not having a...,(~([A-Za-z]))|((dog).*(.).*)
329031,translate English to Regex: lines with a vowel...,"(([AEIOUaeiou]){5,}).*(.*[A-Z].*).*"
329040,translate English to Regex: lines with the str...,((dog).*([AEIOUaeiou]).*)|((truck)&(ring))
329041,translate English to Regex: lines with the str...,((dog)|([AEIOUaeiou])).*((truck)|([a-z])|(ring...

In [8]:
new_df.to_csv("labeled_data_huge.csv", index=None)

In [23]:
kb13_regex = pd.read_csv('../datasets/NL-RX-Turk/targ.txt', sep='\n', header=None).rename(columns={0:'regex'})
kb13_label = pd.read_csv('../datasets/NL-RX-Turk/src.txt', sep='\n', header=None).rename(columns={0:'label'})
df = pd.concat([kb13_label, kb13_regex], axis=1)
df['label'] = 'translate English to Regex: ' + df['label']
df

,label,regex
0,translate English to Regex: Lines that have wo...,\b([A-Z])&([AEIOUaeiou])\b
1,translate English to Regex: Lends that end wit...,((.*)(.)).*(dog).*
2,translate English to Regex: lines that have ei...,.*([A-Za-z])|(.).*
3,translate English to Regex: Items with a numer...,([0-9]).*(([A-Za-z])&([a-z])).*
4,translate English to Regex: lines with the str...,".*(dog){2,}.*"
...,...,...
9995,translate English to Regex: lines containing a...,\b([A-Za-z])|(.)|(dog)\b
9996,translate English to Regex: lines with the str...,((dog)|([A-Za-z]))*
9997,translate English to Regex: lines with capital...,(([A-Z])|(~([0-9])))*
9998,translate English to Regex: lines that does no...,.*~((dog)&(.)).*
9999,translate English to Regex: lines that don't o...,~(([A-Za-z])+)

In [24]:
df.to_csv("labeled_nlrx_turk.csv", index=None)